<template>
    <div class='terms'>
        <div class='content'>
            <div class='content_section'>
                <p class='text text-indent'>
                    These Terms & Conditions of Use is entered into between you (hereinafter referred to as “you” or “your”) and Vitatoken (as defined below). By accessing, downloading, using or clicking on “I agree” to accept any Vitatoken Services (as defined below) provided by Vitatoken (as defined below), you agree that you have read, understood and accepted all of the terms and conditions stipulated in these Terms of Use (hereinafter referred to as “these Terms”) as well as our Privacy Policy at www.vitatoken.io. In addition, when using some features of the Services, you may be subject to specific additional terms and conditions applicable to those features.
                </p>
                <p class='text text-indent'>
                    Please read the terms carefully as they govern your use of Vitatoken Services.These clauses contain important clauses, including arbitration clauses requiring the settlement of all claims through legally binding arbitration.The terms of the arbitration provision are set forth in Article 10, “Resolving Disputes: Forum, Arbitration, Class Action Waiver”, hereunder. As with any asset, the values of Digital Currencies (as defined below) may fluctuate significantly and there is a substantial risk of economic losses when purchasing, selling, holding or investing in Digital Currencies and their derivatives.
                </p>
                <p class='text text-indent'>
                    By using the vitatoken service, you acknowledge and agree that: (1) You are aware of the risks associated with transactions of digital currencies and their derivatives;(2) You shall assume all risks related to the use of vitatoken services and transactions of digital currencies and their derivatives; (3) Vitatoken shall not be liable for any such risks or adverse outcomes.
                </p>
                <p class='text text-indent'>
                    By accessing, using or attempting to use Vitatoken Services in any capacity, you acknowledge that you accept and agree to be bound by these Terms. If you do not agree, do not access Vitatoken or utilize Vitatoken services.
                </p>
            </div>
            <div v-for='(item) in contentList' :key='item.index' class='content_section'>
                <p class='title'>
                    {{ item.title }}
                </p>
                <p v-for='(items,index) in item.textList' :key='index'>
                    <span v-if='items.algin' class='text'>
                        {{ items.text }}
                    </span>
                    <span v-else class='text text-indent'>
                        {{ items }}
                    </span>
                </p>
            </div>
        </div>
    </div>
</template>

<script>
export default {
    setup () {
        const contentList = [
            {
                index: 'I',
                title: 'I. Definitions',
                textList: [
                    'Vitatoken refers to an ecosystem comprising Vitatoken websites (whose domain names include but are not limited to www.vitatoken.io) mobile applications, clients, applets and other applications that are developed to offer Vitatoken Services, and includes independently-operated platforms, websites and clients within the ecosystem. In case of any inconsistency between relevant terms of use of the above platforms and the contents of these Terms, the respective applicable terms of such platforms shall prevail.',
                    'Unincorporated organizations and teams that provide Vitatoken Services and are responsible for such services. For convenience, unless otherwise stated, references to “Vitatoken” and “we” in these Terms specifically mean Vitatoken  Operators. Under these terms, Vitatoken operators may change as Vitatoken’s business adjusts, in which case, the changed operators shall perform their obligations under these terms with you and provide services to you, and such change does not affect your rights and interests under these terms. additionally, the scope of vitatoken operators may be expanded due to the provision of new vitatoken services, in which case, if you continue to use vitatoken services, it is deemed that you have agreed to jointly execute these terms with the newly added vitatoken operators. in case of a dispute, you shall determine the entities by which these terms are performed with you and the counterparties of the dispute, depending on the specific services you use and the particular actions that affect your rights or interests.',
                    'Vitatoken Services refer to various services provided to you by Vitatoken that are based on Internet and/or blockchain technologies and offered via Vitatoken websites, mobile applications, clients and other forms (including new ones enabled by future technological development). Vitatoken Services include but are not limited to such Vitatoken ecosystem and existing services offered by Trust Wallet and novel services to be provided by Vitatoken.',
                    'Vitatoken Platform Rules refer to all rules, interpretations, announcements, statements, letters of consent and other contents that have been and will be subsequently released by Vitatoken, as well as all regulations, implementation rules, product process descriptions, and announcements published in the Help Center or within products or service processes.',
                    'Users refer to all individuals, institutions or organizations that access, download or use Vitatoken or Vitatoken Services and who meet the criteria and conditions stipulated by Vitatoken. If there exist other agreements for such entities as developers, distributors, market makers, and Digital Currencies exchanges, such agreements shall be followed.',
                    'Digital Currencies refer to encrypted or digital tokens or cryptocurrencies with a certain value that are based on blockchain and cryptography technologies and are issued and managed in a decentralized form. Digital Assets refer to Digital Currencies, their derivatives or other types of digitalized assets with a certain value.',
                    'Vitatoken Accounts refer to the foundational virtual accounts, including main accounts and subaccounts, which are opened by Vitatoken for Users to record on Vitatoken their usage of Vitatoken Services, transactions, asset changes and basic information. Vitatoken Accounts serve as the basis for Users to enjoy and exercise their rights on Vitatoken. Crypto-to-crypto Trading refers to spot transactions in which one digital currency is exchanged for another digital currency.',
                    'Fiat Trading refers to spot transactions in which Digital Currencies are exchanged for fiat currencies or vice versa.',
                    'Collateral Accounts refer to special accounts opened by Users on Vitatoken to deposit and withdraw collateral (such as margins) in accordance with these Terms, as required for contract transactions, leveraged trading and/or currency borrowing services.',
                    'Loan/Lending refers to Vitatoken’s lending of Digital Currencies to Users at an interest collected in certain ways (in the form of Digital Currencies), including but not limited to the leveraged trading and currency lending services currently offered, and other forms of loan/lending services to be launched by Vitatoken.',
                ]
            },
            {
                index: 'II',
                title: 'II. General Provisions',
                textList: [
                    {
                        algin: 'left',
                        text: 'About These Terms:'
                    },
                    'a. Contractual Relationship',
                    'These Terms constitute a legal agreement and create a binding contract between you and Vitatoken Operators.',
                    'b. Supplementary Terms',
                    'Due to the rapid development of Digital Currencies and Vitatoken, these Terms between you and Vitatoken Operators do not enumerate or cover all rights and obligations of each party, and do not guarantee full alignment with needs arising from future development. Therefore, THE PRIVACY POLICY, VITATOKEN PLATFORM RULES, AND ALL OTHER AGREEMENTS ENTERED INTO SEPARATELY BETWEEN YOU AND VITATOKEN ARE DEEMED SUPPLEMENTARY TERMS THAT ARE AN INTEGRAL PART OF THESE TERMS AND SHALL HAVE THE SAME LEGAL EFFECT. YOUR USE OF VITATOKEN SERVICES IS DEEMED YOUR ACCEPTANCE OF THE ABOVE SUPPLEMENTARY TERMS.',
                    'c. Changes to These Terms',
                    'Vitatoken reserves the right to change or modify these Terms in its discretion at any time. Vitatoken will notify such changes by updating the terms on its website (www.vitatoken.io) and modifying the 11/2/2022 date displayed on this page.ANY AND ALL MODIFICATIONS OR CHANGES TO THESE TERMS WILL BECOME EFFECTIVE UPON PUBLICATION ON THE WEBSITE OR RELEASE TO USERS. THEREFORE, YOUR CONTINUED USE OF VITATOKEN SERVICES IS DEEMED YOUR ACCEPTANCE OF THE MODIFIED AGREEMENT AND RULES. IF YOU DO NOT AGREE TO ANY CHANGES TO THESE TERMS, YOU MUST STOP USING VITATOKEN SERVICES IMMEDIATELY. YOU ARE RECOMMENDED TO FREQUENTLY REVIEW THESE TERMS TO ENSURE YOUR UNDERSTANDING OF THE TERMS AND CONDITIONS THAT APPLY TO YOUR ACCESS TO AND USE OF Vitatoken SERVICES.',
                    'd. Prohibition of Use',
                    'BY ACCESSING AND USING VITATOKEN SERVICES, YOU REPRESENT AND WARRANT THAT YOU HAVE NOT BEEN INCLUDED IN ANY TRADE EMBARGOES OR ECONOMIC SANCTIONS LIST (SUCH AS THE UNITED NATIONS SECURITY COUNCIL SANCTIONS LIST), THE LIST OF SPECIALLY DESIGNATED NATIONALS MAINTAINED BY OFAC (THE OFFICE OF FOREIGN ASSETS CONTROL OF THE U.S. DEPARTMENT OF THE TREASURY),OR THE DENIED PERSONS OR ENTITY LIST OF THE U.S. DEPARTMENT OF COMMERCE. VITATOKEN RESERVES THE RIGHT TO CHOOSE MARKETS AND JURISDICTIONS TO CONDUCT BUSINESS, AND MAY RESTRICT OR REFUSE, IN ITS DISCRETION,THE PROVISION OF VITATOKEN SERVICES IN CERTAIN COUNTRIES OR REGIONS.',
                    {
                        algin: 'left',
                        text: 'About Vitatoken'
                    },
                    'As an important part of the Vitatoken Ecosystem, Vitatoken mainly serves as a global online platform for Digital Assets trading, and provides Users with a trading platform, financing services, technical services and other Digital Assets-related services. As further detailed in Article 3 below, Users must register and open an account with Vitatoken,and deposit Digital Assets into their account prior to trading. Users may, subject to the restrictions set forth in these Terms, apply for the withdrawal of Digital Assets.',
                    'Although Vitatoken has been committed to maintaining the accuracy of the information provided through Vitatoken Services, Vitatoken cannot and does not guarantee its accuracy, applicability, reliability, integrity, performance or appropriateness, nor shall Vitatoken be liable for any loss or damage that may be caused directly or indirectly by your use of these contents. The information about Vitatoken Services may change without notice, and the main purpose of providing such information is to help Users make independent decisions.Vitatoken does not provide investment or consulting advice of any kind, and is not responsible for the use or interpretation of information on Vitatoken or any other communication medium. All Users of Vitatoken Services must understand the risks involved in Digital Assets trading, and are recommended to exercise prudence and trade responsibly within their own capabilities.',
                    {
                        algin: 'left',
                        text: 'Vitatoken Account Registration and Requirements'
                    },
                    'a. Registration',
                    ' All Users must apply for a Vitaoken Account at (www.vitatoken.io) before using Vitatoken Services. When you register a Vitatoken Account, you must provide the information identified in this paragraph 3 or otherwise as requested by Vitatoken, and accept these Terms, the Privacy Policy, and other Vitatoken Platform Rules. Vitatoken may refuse, in its discretion, to open a Vitatoken Account for you. You agree to provide complete and accurate information when opening a Vitatoken Account, and agree to timely update any information you provide to Vitatoken to maintain the integrity and accuracy of the information. Each User (including natural person, business or legal entity) may maintain only one main account at any given time. However, Users can open one or more subaccounts under the main account with the consent of Vitatoken. For certain Vitatoken Services, you may be required to set up a specific account independent from your Vitatoken Account, based on the provisions of these Terms or the Supplementary Terms. The registration, use, protection and management of such trading accounts are equally governed by the provisions of this Section and Section VI, unless otherwise stated in these Terms or the Supplementary Terms.',
                    'b. Eligibility',
                    'By registering to use a Vitatoken Account, you represent and warrant that (i) as an individual, you are at least 18 or are of legal age to form a binding contract under applicable laws; (ii) as an individual, legal person, or other organization, you have full legal capacity and sufficient authorizations to enter into these Terms; (iii) you have not been previously suspended or removed from using Vitatoken Services; (iv) you do not currently have a Vitatoken Account;(v) you are neither a United States user, a Malaysia user, a Singapore-based user, or an Ontario (Canada)-based user;nor are you acting on behalf of a United States user, a Malaysia user, a Singapore-based user, or an Ontario (Canada)-based user. If you act as an employee or agent of a legal entity, and enter into these Terms on their behalf,you represent and warrant that you have all the necessary rights and authorizations to bind such legal entity; (vi) your use of Vitatoken Services will not violate any and all laws and regulations applicable to you, including but not limited to regulations on anti-money laundering, anti-corruption, and counter-terrorist financing.',
                    'Please note that some products and services may not be available in certain jurisdictions or regions or to certain users. Vitatoken reserves the right to change, modify or impose additional restrictions at its discretion at any time.Futures and Derivatives Products. USDⓈ-M Futures, Coin-M Futures, Margin, Vitatoken Options, Vanilla Options and Leveraged Tokens (“Futures and Derivatives Products”) will not be available to all users of the Netherlands, Germany,Italy, Australia and Hong Kong, and retail users of the United Kingdom.Crypto Tokens. Privacy tokens (XMR, ZEC, DASH, XVG, XZC, KMD, ZEN, PIVX and GRS) will not be available to users of Australia with PayID associated with the Vitatoken accounts.',
                    'c. User Identity Verification',
                    'Your registration of an account with Vitatoken will be deemed your agreement to provide required personal information for identity verification. Such information will be used to verify Users’ identity, identify traces of money laundering,terrorist financing, fraud and other financial crimes through Vitatoken, or for other lawful purposes stated by Vitatoken. We will collect, use and share such information in accordance with our Privacy Policy. In addition to providing such information, you agree to allow us to keep a record of that information during the period for which your account is active and within five (5) years after your account is closed, in compliance with global industry standards on data storage. You also authorize us to conduct necessary investigations directly or through a third party to verify your identity or protect you and/or us from financial crimes, such as fraud. The information we require to verify your identity may include, but is not limited to, your name, email address, contact information, phone number, username,government-issued ID, date of birth, and other information collected during account registration. When providing the required information, you confirm it is true and accurate. AFTER REGISTRATION, YOU MUST ENSURE THAT THE INFORMATION IS TRUE, COMPLETE, AND TIMELY UPDATED WHEN CHANGED. IF THERE ARE ANY GROUNDS FOR BELIEVING THAT ANY OF THE INFORMATION YOU PROVIDED IS INCORRECT, FALSE, OUTDATED OR INCOMPLETE, VITATOKEN RESERVES THE RIGHT TO SEND YOU A NOTICE TO DEMAND CORRECTION, DIRECTLY DELETE THE RELEVANT INFORMATION, AND, AS THE CASE MAY BE, TERMINATE ALL OR PART OF VITATOKEN SERVICES WE PROVIDE FOR YOU. IF WE ARE UNABLE TO REACH YOU WITH THE CONTACT INFORMATION YOU PROVIDED, YOU SHALL BE FULLY LIABLE FOR ANY LOSS OR EXPENSE CAUSED TO VITATOKEN DURING YOUR USE OF VITATOKEN SERVICES. YOU HEREBY ACKNOWLEDGE AND AGREE THAT YOU HAVE THE OBLIGATION TO UPDATE ALL THE INFORMATION IF THERE IS ANY CHANGE.BY REGISTERING AN ACCOUNT, YOU HEREBY AUTHORIZE VITATOKEN TO CONDUCT INVESTIGATIONS THAT VITATOKEN CONSIDERS NECESSARY, EITHER DIRECTLY OR THROUGH A THIRD PARTY, TO VERIFY YOUR IDENTITY OR PROTECT YOU, OTHER USERS AND/OR VITATOKEN FROM FRAUD OR OTHER FINANCIAL CRIMES,AND TO TAKE NECESSARY ACTIONS BASED ON THE RESULTS OF SUCH INVESTIGATIONS. YOU ALSO ACKNOWLEDGE AND AGREE THAT YOUR PERSONAL INFORMATION MAY BE DISCLOSED TO CREDIT BUREAUS AND AGENCIES FOR FRAUD PREVENTION OR FINANCIAL CRIME PREVENTION,WHICH MAY RESPOND TO OUR INVESTIGATIONS IN FULL.',
                    'd. Account Usage Requirements',
                    'The Vitatoken Account can only be used by the account registrant. Vitatoken reserves the right to suspend, freeze or cancel the use of Vitatoken Accounts by persons other than account registrant. If you suspect or become aware of any unauthorized use of your username and password, you should notify Vitatoken immediately. Vitatoken assumes no liability for any loss or damage arising from the use of Vitatoken Account by you or any third party with or without your authorization.',
                    'e. Account Security',
                    'Vitatoken has been committed to maintaining the security of User entrusted funds, and has implemented industry standard protection for Vitatoken Services. However, the actions of individual Users may pose risks. You shall agree to treat your access credentials (such as username and password) as confidential information, and not to disclose such information to any third party. You also agree to be solely responsible for taking the necessary security measures to protect your Vitatoken Account and personal information.You should be solely responsible for keeping safe of your Vitatoken Account and password, and be responsible for all the transactions under your Vitatoken Account. Vitatoken assumes no liability for any loss or consequences caused by authorized or unauthorized use of your account credentials, including but not limited to information disclosure,information release, consent or submission of various rules and agreements by clicking on the website, online agreement renewal, etc.By creating a Vitatoken Account, you hereby agree that:you will notify Vitatoken immediately if you are aware of any unauthorized use of your Vitatoken Account and password or any other violation of security rules;you will strictly abide by all mechanisms or procedures of Vitatoken regarding security, authentication, trading,charging, and withdrawal; and you will take appropriate steps to logout from Vitatoken at the end of each visit.',
                    'f. Personal Data',
                    'Your personal data will be properly protected and kept confidential, but Vitatoken has the right to collect, process,use or disclose your personal data in accordance with the Terms (including the Privacy Policy) or applicable laws.Depending on the products or services concerned, your personal data may be disclosed to the following third parties:your transaction counterparty;Vitatoken Operators, and the shareholders, partners, investors, directors, supervisors, senior managers and employees of such entities;our joint ventures, alliance partners and business partners;our agents, contractors, suppliers, third-party service providers and professional advisers, including the parties who have been contracted to provide us with administrative, financial, research, operations, IT and other services, in such areas as telecommunications, information technology, payroll, information processing, training, market research, storage and archival;third-party business partners who provide goods and services or sponsor contests or other promotional activities, whether or not in cooperation with us;insurance companies or insurance investigators and credit providers;credit bureaus, or any debt collection agencies or dispute resolution centers in the event of violation or dispute;business partners, investors, trustees or assignees (actual or expected) that promote business asset transactions (which can be broadened to include any merger, acquisition or asset sale) of Vitatoken Operators; professional consultants such as auditors and lawyers;relevant government regulatory agencies or law enforcement agencies to comply with laws or regulations formulated by government authorities;assignees of our rights and obligations;banks, credit card companies and their respective service providers; persons with your consent as determined by you or the applicable contract.',
                ]
            },
            {
                index: 'III',
                title: 'III. Vitatoken Services',
                textList: [
                    'Upon completion of the registration and identity verification for your Vitatoken Account, you may use various Vitatoken Services, including but not limited to, Crypto-to-crypto Trading, Fiat Trading, contract trading, leveraged trading, Vitatoken Savings services, staking, acquiring market-related data, research and other information released by Vitatoken, participating in User activities held by Vitatoken, etc., in accordance with the provisions of these Terms (including Vitatoken Platform Rules and other individual agreements). Vitatoken has the right to: Provide, modify or terminate, in its discretion, any Vitatoken Services based on its development plan; and Allow or prohibit some Users’ use of any Vitatoken Services in accordance with relevant Vitatoken Platform Rules.',
                    {
                        algin: 'left',
                        text: 'Service Usage Guidelines'
                    },
                    'a. License ',
                    'Provided that you constantly comply with the express terms and conditions stated in these Terms, Vitatoken grants you a revocable, limited, royalty-free, non-exclusive, non-transferable, and non-sublicensable license to access and use Vitatoken Services through your computer or Internet compatible devices for your personal/internal purposes. You are prohibited to use Vitatoken Services for resale or commercial purposes, including transactions on behalf of other persons or entities. All the above actions are expressly prohibited and constitute a material violation of these Terms. The content layout, format, function and access rights regarding Vitatoken Services should be stipulated in the discretion of Vitatoken. Vitatoken reserves all rights not expressly granted in these Terms. Therefore, you are hereby prohibited from using Vitatoken Services in any way not expressly authorized by these Terms.',
                    'These Terms only grant a limited license to access and use Vitatoken Services. Therefore, you hereby agree that when you use Vitatoken Services, Vitatoken does not transfer Vitatoken Services or the ownership or intellectual property rights of any Vitatoken intellectual property to you or anyone else. All the text, graphics, user interfaces, visual interface, photos, sounds, process flow diagrams, computer code (including html code), programs, software, products, information and documents, as well as the design, structure, selection, coordination, expression, look and feel, and layout of any content included in the services or provided through Vitatoken Services, are exclusively owned, controlled and/or licensed by Vitatoken Operators or its members, parent companies, licensors or affiliates.',
                    'Vitatoken owns any feedback, suggestions, ideas, or other information or materials (hereinafter collectively referred to as “Feedback”) about Vitatoken or Vitatoken Services that you provide through email, Vitatoken Services, or other ways. You hereby transfer all rights, ownership and interests of the Feedback and all related intellectual property rights to Vitatoken. You have no right and hereby waive any request for acknowledgment or compensation based on any Feedback, or any modifications based on any Feedback.',
                    'b. Restriction',
                    'When you use Vitatoken Services, you agree and undertake to comply with the following provisions: During the use of Vitatoken Services, all activities you carry out should comply with the requirements of applicable laws and regulations, these Terms, and various guidelines of Vitatoken; Your use of Vitatoken Services should not violate public interests, public morals, or the legitimate interests of others, including any actions that would interfere with, disrupt, negatively affect, or prohibit other Users from using Vitatoken Services; You agree not to use the services for market manipulation (such as pump and dump schemes, wash trading, self-trading, front running, quote stuffing, and spoofing or layering, regardless of whether prohibited by law); Without written consent from Vitatoken, the following commercial uses of Vitatoken data are prohibited: Trading services that make use of Vitatoken quotes or market bulletin board information. Data feeding or streaming services that make use of any market data of Vitatoken. Any other websites/apps/services that charge for or otherwise profit from (including through advertising or referral fees) market data obtained from Vitatoken.',
                    'Without prior written consent from Vitatoken, you may not modify, replicate, duplicate, copy, download, store, further transmit, disseminate, transfer, disassemble, broadcast, publish, remove or alter any copyright statement or label, or license, sub-license, sell, mirror, design, rent, lease, private label, grant security interests in the properties or any part of the properties, or create their derivative works or otherwise take advantage of any part of the properties. You may not (i) use any deep linking, web crawlers, bots, spiders or other automatic devices, programs, scripts, algorithms or methods, or any similar or equivalent manual processes to access, obtain, copy or monitor any part of the properties, or replicate or bypass the navigational structure or presentation of Vitatoken Services in any way, in order to obtain or attempt to obtain any materials, documents or information in any manner not purposely provided through Vitatoken Services; (ii) attempt to access any part or function of the properties without authorization, or connect to Vitatoken Services or any Vitatoken servers or any other systems or networks of any Vitatoken Services provided through the services by hacking, password mining or any other unlawful or prohibited means; (iii) probe, scan or test the vulnerabilities of Vitatoken Services or any network connected to the properties, or violate any security or authentication measures on Vitatoken Services or any network connected to Vitatoken Services; (iv) reverse look-up, track or seek to track any information of any other Users or visitors of Vitatoken Services; (v) take any actions that imposes an unreasonable or disproportionately large load on the infrastructure of systems or networks of Vitatoken Services or Vitatoken, or the infrastructure of any systems or networks connected to Vitatoken services; (vi) use any devices, software or routine programs to interfere with the normal operation of Vitatoken Services or any transactions on Vitatoken Services, or any other person’s use of Vitatoken Services; (vii) forge headers, impersonate, or otherwise manipulate identification, to disguise your identity or the origin of any messages or transmissions you send to Vitatoken, or (viii) use Vitatoken Services in an illegal way.',
                    'By accessing Vitatoken Services, you agree that Vitatoken has the right to investigate any violation of these Terms, unilaterally determine whether you have violated these Terms, and take actions under relevant regulations without your consent or prior notice. Examples of such actions include, but are not limited to: Blocking and closing order requests; Freezing your account; Reporting the incident to the authorities; Publishing the alleged violations and actions that have been taken; Deleting any information you published that are found to be violations.',
                    {
                        algin: 'left',
                        text: 'Crypto-to-crypto Trading'
                    },
                    'Upon completion of the registration and identity verification for your Vitatoken Account, you may conduct Crypto-to-crypto Trading on Vitatoken in accordance with the provisions of these Terms and Vitatoken Platform Rules.',
                    'a. Orders',
                    'Upon sending an instruction of using Vitatoken Services for Crypto-to-crypto Trading (an “Order”), your account will be immediately updated to reflect the open Orders, and your Orders will be included in Vitatoken’s order book to match other users’ Orders. If one of your Orders fully or partially matches another user’s Order, Vitatoken will execute an exchange (a “Transaction”). Once the Transaction is executed, your account will be updated to reflect that the Order has been fully executed and closed, or the Order has been partially executed. The Order will remain uncompleted until it is fully executed or cancelled under paragraph (b) below. To conclude a Transaction, you authorize Vitatoken to temporarily control the Digital Currencies involved in your Transaction.',
                    'b. Cancellation',
                    'For Orders initiated through Vitatoken Services, you may only cancel them before they have been matched with other Users’ Orders. Once your Order has been matched with another user’s Order, you may not change, revoke or cancel Vitatoken’s authorization to complete the Order. For any partially matched Order, you may cancel the unmatched part of the Order unless such portion has been matched. Vitatoken reserves the right to reject any cancellation request related to the Order you have submitted. If your account does not have sufficient amount of Digital Currencies to execute an Order, Vitatoken may cancel the entire Order, or execute part of the Order with the amount of Digital Currencies you have in your account (in each case, any Transaction related fees payable to Vitatoken are deducted as stated in paragraph (c) below).',
                    'c. Fees',
                    'You agree to pay Vitatoken the fees specified in www.vitatoken.io. Vitatoken may, in its discretion, update the fees at any time. Any updated fees will apply to any sales or other Transactions that occur following the effective date of the updated fees. You authorize Vitatoken to deduct from your account any applicable fees that you owe under these Terms.',
                    'd. Other Types of Crypto-to-crypto Trading',
                    'In addition to the Crypto-to-crypto Trading that allows users to directly place orders as mentioned in paragraph (a) above, Vitatoken may, in its discretion, provide technical and platform services for other types of Crypto-to-crypto Trading under its separately formulated Vitatoken Platform Rules, such as One Cancels the Other (OCO) and block trade. Fiat Trading Prior to conducting Fiat Trading, in accordance with type of fiat trading, you shall separately read and agree User Agreements with various Vitatoken partnered OTC platforms, and comply with the Legal Statement, Privacy Policy, P2P User Transaction Policy (www.vitatoken.io) and other specific Vitatoken Platform Rules related to Fiat Trading as well as the business rules of such partners, and open an account on such Vitatoken OTC platforms, following the completion of the registration and identity verification for your Vitatoken Account, if applicable. a. Fiat Payments. If you choose to utilise the Fiat Trading, you agree that Vitatoken (registration number: 1983683) having its registered office at Vistra Coperate Services Centre, Wickhams Cay II, Road Town, Tortola, VG1110, British Virgin Islands shall be the main Vitatoken Operator responsible for the transaction (including for the purpose of refunds and cancellations). The activities of Vitatoken defined herein are governed by the laws of the British Virgin Islands.',
                    {
                        algin: 'left',
                        text: 'Futures Trading'
                    },
                    'Unless otherwise specified by Vitatoken, to conduct Futures Trading, you must conclude with Vitatoken a separate Vitatoken Futures Service Agreement (www.vitatoken.io) and open a special Collateral Account, following the completion of registration and identity verification for your Vitatoken Account. You acknowledge and agree that:',
                    'a. You fully understand the high risks of Futures Trading, including but not limited to the risk of major fluctuations of Digital Assets in Futures Trading, and the risk of exacerbated adverse outcome when leverage is used;',
                    'b. You have sufficient investment knowledge and experience and the capacity to take risks arising from Futures Trading, and agree to independently assume all the risks arising from the investment of Futures Trading;',
                    'c. Before performing Futures Trading, you have read and understood all the contents of the Vitatoken Futures Service Agreement and the relevant Vitatoken Platform Rules, and have consulted relevant professionals to make informed decisions on whether and how to complete Futures Trading according to their recommendations and your own reasonable judgment;',
                    'd. You agree and authorize Vitatoken to take various reasonable measures in its discretion (including but not limited to forced liquidation and forced position reduction under specific circumstances) in accordance with the Vitatoken Futures Service Agreement and the relevant Vitatoken Platform Rules to protect the legitimate interests of you, Vitatoken and other Users.',
                    {
                        algin: 'left',
                        text: 'Options Trading'
                    },
                    'You acknowledge and agree that:',
                    'a. You fully understand the high risks of Options Trading, including but not limited to the risk of major fluctuations of Digital Assets in Options Trading, and the risk of exacerbated adverse outcome when leverage is used;',
                    'b. You have sufficient investment knowledge and experience and the capacity to take risks arising from Options Trading, and agree to independently assume all the risks arising from the investment of Options Trading;',
                    'c. Before performing Options Trading, you have read and understood all the relevant Vitatoken Platform Rules, and have consulted relevant professionals to make informed decisions on whether and how to complete Options Trading according to their recommendations and your own reasonable judgment;',
                    'd. You agree and authorize Vitatoken to take various reasonable measures in its discretion (including but not limited to forced liquidation and forced position reduction under specific circumstances) in accordance with the relevant Vitatoken Platform Rules to protect the legitimate interests of you, Vitatoken and other Users.',
                    'Margins Trading',
                    'Unless otherwise specified by Vitatoken, prior to conducting Margins Trading, you must open a special Collateral Account and/or complete other related procedures, following the completion of registration and identity verification for your Vitatoken Account.',
                    'a. Risks of Margins Trading',
                    'Margins Trading is highly risky. As a leveraged trader, you acknowledge and agree that you access and use Margins Trading and borrowing services at your own risk, which include but are not limited to: The liquidity, market depth and dynamics of the trading market fluctuate violently and change rapidly. The use of leverage may work to your advantage or disadvantage, which may result in major gains or losses as the case may be. You are not eligible to receive forked currencies split from any blockchain assets in your Collateral Account, even if you have not engaged in any Margins Trading or borrowing at all. Loans carry risk, and the value of your blockchain assets may decline. If the value of your assets drops to a certain level, you are responsible for dealing with these market circumstances. In some market situations, you may find it difficult or impossible to liquidate a position. This may occur, for example, as a result of insufficient market liquidity or technical issues on Vitatoken. Placing contingent Orders does not necessarily limit your losses to the expected amount, as market conditions may prevent you from executing such orders. Margins Trading does not have guaranteed measures against losses. As a borrower, you may suffer losses that exceed the amount you deposited into your Collateral Account.',
                    'b. To start Margins Trading:',
                    'You represent and warrant that you are neither from the U.S. nor on any list of trade embargoes or economic sanctions, such as the Specially Designated National by OFAC (The Office of Foreign Assets Control of the U.S. Department of the Treasury).You should fully understand the risks associated with Margins Trading and Lending, and be fully responsible for any trading and non-trading activities under your Vitatoken Account and Collateral Account. You should not engage in Transactions or invest in funds that are beyond your financial capacities; You are fully responsible for knowing the true status of any position, even if Vitatoken may present it incorrectly at any time; You agree to keep enough Digital Assets in your Collateral Account, as required by Vitatoken for Users’ engagement in Margins Trading, and promptly repay your loan in full. Failure to keep enough assets or to timely repay the outstanding loan may result in forced liquidation of the assets in your Collateral Account; Even if with the ability to forcefully liquidate any position, Vitatoken cannot guarantee to stop losses. If your assets are insufficient to repay the outstanding loan after the liquidation of your position, you are still liable for any further shortfall of assets; Vitatoken may take measures, in its discretion and on your behalf, to reduce your potential losses, including but not limited to, transferring assets from your Collateral Account into your Vitatoken Account and/or vice versa; During Vitatoken system maintenance, you agree to be fully responsible for managing your Collateral Account under risks, including but not limited to, closing positions and repaying your loan.',
                    'You, agree to conduct all Transactions, Margins Trading and/or borrowing on your own, and be fully responsible for your activities. Vitatoken assumes no liability for any loss or damage caused by your use of any Vitatoken services or your unawareness of the risks associated with the use of Digital Assets or with your use of Vitatoken Services.'
                ]

            },
            {
                index: 'IV',
                title: 'IV. Liabilities',
                textList: [
                    'Disclaimer of Warranties TO THE MAXIMUM EXTENT PERMITTED UNDER APPLICABLE LAW, VITATOKEN SERVICES, VITATOKEN MATERIALS AND ANY PRODUCT, SERVICE OR OTHER ITEM PROVIDED BY OR ON BEHALF OF VITATOKEN ARE OFFERED ON AN “AS IS” AND “AS AVAILABLE” BASIS, AND VITATOKEN EXPRESSLY DISCLAIMS, AND YOU WAIVE, ANY AND ALL OTHER WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE OR NON-INFRINGEMENT OR WARRANTIES ARISING FROM COURSE OF PERFORMANCE, COURSE OF DEALING OR USAGE IN TRADE. WITHOUT LIMITING THE FOREGOING, VITATOKEN DOES NOT REPRESENT OR WARRANT THAT THE SITE, VITATOKEN SERVICES OR VITATOKEN MATERIALS ARE ACCURATE, COMPLETE, RELIABLE, CURRENT, ERROR-FREE, OR FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. VITATOKEN DOES NOT GUARANTEE THAT ANY ORDER WILL BE EXECUTED, ACCEPTED, RECORDED OR REMAIN OPEN. EXCEPT FOR THE EXPRESS STATEMENTS, AGREEMENTS AND RULES SET FORTH IN THESE TERMS, YOU HEREBY ACKNOWLEDGE AND AGREE THAT YOU HAVE NOT RELIED UPON ANY OTHER STATEMENT OR AGREEMENT, WHETHER WRITTEN OR ORAL, WITH RESPECT TO YOUR USE AND ACCESS OF VITATOKEN SERVICES. WITHOUT LIMITING THE FOREGOING, YOU HEREBY UNDERSTAND AND AGREE THAT VITATOKEN WILL NOT BE LIABLE FOR ANY LOSSES OR DAMAGES ARISING OUT OF OR RELATING TO:',
                    '(A) ANY INACCURACY, DEFECT OR OMISSION OF DIGITAL ASSETS PRICE DATA, (B) ANY ERROR OR DELAY IN THE TRANSMISSION OF SUCH DATA, (C) INTERRUPTION IN ANY SUCH DATA, (D) REGULAR OR UNSCHEDULED MAINTENANCE CARRIED OUT BY VITATOKEN AND SERVICE INTERRUPTION AND CHANGE RESULTING FROM SUCH MAINTENANCE, (E) ANY DAMAGES INCURRED BY OTHER USERS’ ACTIONS, OMISSIONS OR VIOLATION OF THESE TERMS, (F) ANY DAMAGE CAUSED BY ILLEGAL ACTIONS OF OTHER THIRD PARTIES OR ACTIONS WITHOUT AUTHORIZED BY VITATOKEN; AND (G) OTHER EXEMPTIONS MENTIONED IN DISCLAIMERS AND PLATFORM RULES ISSUED BY VITATOKEN. THE DISCLAIMER OF IMPLIED WARRANTIES CONTAINED HEREIN MAY NOT APPLY IF AND TO THE EXTENT IT IS PROHIBITED BY APPLICABLE LAW OF THE JURISDICTION IN WHICH YOU RESIDE.',
                    'Disclaimer of Damages and Limitation of Liability TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT WILL VITATOKEN, ITS AFFILIATES AND THEIR RESPECTIVE SHAREHOLDERS, MEMBERS, DIRECTORS, OFFICERS, EMPLOYEES, ATTORNEYS, AGENTS, REPRESENTATIVES, SUPPLIERS OR CONTRACTORS BE LIABLE FOR ANY INCIDENTAL, INDIRECT, SPECIAL, PUNITIVE, CONSEQUENTIAL OR SIMILAR DAMAGES OR LIABILITIES WHATSOEVER (INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF DATA, INFORMATION, REVENUE, PROFITS OR OTHER BUSINESSES OR FINANCIAL BENEFITS) ARISING OUT OF VITATOKEN SERVICES, ANY PERFORMANCE OR NON-PERFORMANCE OF VITATOKEN SERVICES, OR ANY OTHER PRODUCT, SERVICE OR OTHER ITEM PROVIDED BY OR ON BEHALF OF VITATOKEN AND ITS AFFILIATES, WHETHER UNDER CONTRACT, STATUTE, STRICT LIABILITY OR OTHER THEORY EVEN IF VITATOKEN HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES EXCEPT TO THE EXTENT OF A FINAL JUDICIAL DETERMINATION THAT SUCH DAMAGES WERE A RESULT OF VITATOKEN’S GROSS NEGLIGENCE, FRAUD, WILLFUL MISCONDUCT OR INTENTIONAL VIOLATION OF LAW. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE LIMITATION MAY NOT APPLY TO YOU.',
                    'NOTWITHSTANDING THE FOREGOING, IN NO EVENT WILL THE LIABILITY OF VITATOKEN, ITS AFFILIATES AND THEIR RESPECTIVE SHAREHOLDERS, MEMBERS, DIRECTORS, OFFICERS, EMPLOYEES, ATTORNEYS, AGENTS, REPRESENTATIVES, SUPPLIERS OR CONTRACTORS ARISING OUT OF SERVICES OFFERED BY OR ON BEHALF OF VITATOKEN AND ITS AFFILIATES, ANY PERFORMANCE OR NON-PERFORMANCE OF VITATOKEN SERVICES, OR ANY OTHER PRODUCT, SERVICE OR OTHER ITEM, WHETHER UNDER CONTRACT, STATUTE, STRICT LIABILITY OR OTHER THEORY, EXCEED THE AMOUNT OF THE FEES PAID BY YOU TO VITATOKEN UNDER THESE TERMS IN THE TWELVE-MONTH PERIOD IMMEDIATELY PRECEDING THE EVENT GIVING RISE TO THE CLAIM FOR LIABILITY.',
                    {
                        algin: 'left',
                        text: 'Indemnification'
                    },
                    'You agree to indemnify and hold harmless Vitatoken Operators, their affiliates, contractors, licensors, and their respective directors, officers, employees and agents from and against any claims, actions, proceedings, investigations, demands, suits, costs, expenses and damages (including attorneys’ fees, fines or penalties imposed by any regulatory authority) arising out of or related to (i) your use of, or conduct in connection with, Vitatoken Services, (ii) your breach or our enforcement of these Terms, or (iii) your violation of any applicable law, regulation, or rights of any third party during your use of Vitatoken Services. If you are obligated to indemnify Vitatoken Operators, their affiliates, contractors, licensors, and their respective directors, officers, employees or agents pursuant to these Terms, Vitatoken will have the right, in its sole discretion, to control any action or proceeding and to determine whether Vitatoken wishes to settle, and if so, on what terms.',
                ]
            },
            {
                index: 'V',
                title: 'V. Announcements',
                textList: [
                    'Please be aware that all official announcements, news, promotions, competitions and airdrops will be listed on www.vitatoken.io. USERS UNDERTAKE TO REFER TO THESE MATERIALS REGULARLY AND PROMPTLY. VITATOKEN WILL NOT BE HELD LIABLE OR RESPONSIBLE IN ANY MANNER OF COMPENSATION SHOULD USERS INCUR PERSONAL LOSSES ARISING FROM IGNORANCE OR NEGLIGENCE OF THE ANNOUNCEMENTS.',
                ]
            },
            {
                index: 'VI',
                title: 'VI. Termination of Agreement',
                textList: [
                    {
                        algin: 'left',
                        text: 'Suspension of Vitatoken Accounts'
                    },
                    'You agree that Vitatoken shall have the right to immediately suspend your Vitatoken Account (and any accounts beneficially owned by related entities or affiliates), freeze or lock the Digital Assets or funds in all such accounts, and suspend your access to Vitatoken for any reason including if Vitatoken suspects any such accounts to be in violation of these Terms, our Privacy Policy, or any applicable laws and regulations. You agree that Vitatoken shall not be liable to you for any permanent or temporary modification of your Vitatoken Account, or suspension or termination of your access to all or any portion of Vitatoken Services. Vitatoken shall reserve the right to keep and use the transaction data or other information related to such Vitatoken Accounts. The above account controls may also be applied in the following cases:',
                    'The Vitatoken Account is subject to a governmental proceeding, criminal investigation or other pending litigation;',
                    'We detect unusual activities in the Vitatoken Account;',
                    'We detect unauthorized access to the Vitatoken Account;',
                    'We are required to do so by a court order or command by a regulatory/government authority.',
                    {
                        algin: 'left',
                        text: 'Cancellation of Vitatoken Accounts'
                    },
                    'In case of any of the following events, Vitatoken shall have the right to directly terminate these Terms by cancelling your Vitatoken Account, and shall enjoy the right but not the obligation to permanently freeze (cancel) the authorizations of your Vitatoken Account on Vitatoken and withdraw the corresponding Vitatoken Account thereof: after Vitatoken terminates services to you; you allegedly register or register in any other person’s name as a Vitatoken User again, directly or indirectly; the information that you have provided is untruthful, inaccurate, outdated or incomplete; when these Terms are amended, you state your unwillingness to accept the amended Terms by applying for cancellation of your Vitatoken Account or by other means; you request that Vitatoken Services be terminated; and any other circumstances where Vitatoken deems it should terminate Vitatoken Services.',
                    'Should your Vitatoken Account be terminated, the account and transactional information that meet data retention standards will be securely stored for 5 years. In addition, if a transaction is unfinished during the account termination process, Vitatoken shall have the right to notify your counterparty of the situation at that time. You acknowledge that a user-initiated account exit (right to erasure under GDPR or other equivalent regulations) will also be subjected to the termination protocol stated above.',
                    'If Vitatoken is informed that any Digital Assets or funds held in your Vitatoken Account are stolen or otherwise are not lawfully possessed by you, Vitatoken may, but has no obligation to, place an administrative hold on the affected funds and your Vitatoken Account. If Vitatoken does lay down an administrative hold on some or all of your funds or Vitatoken Account, Vitatoken may continue such hold until such time as the dispute has been resolved and evidence of the resolution acceptable to Vitatoken has been provided to Vitatoken in a form acceptable to Vitatoken. Vitatoken will not involve itself in any such dispute or the resolution of the dispute. You agree that Vitatoken will have no liability or responsibility for any such hold, or for your inability to withdraw Digital Assets or funds or execute trades during the period of any such hold.',
                    {
                        algin: 'left',
                        text: 'Remaining Funds After Vitatoken Account Termination'
                    },
                    'Except as set forth in paragraph 4 below, once a Vitatoken Account is closed/withdrawn, all remaining account balance (which includes charges and liabilities owed to Vitatoken) will be payable immediately to Vitatoken. Upon payment of all outstanding charges to Vitatoken (if any), Users will have 5 business days to withdraw all Digital Assets or funds from the account.',
                    'Remaining Funds After Vitatoken Account Termination Due to Fraud, Violation of Law, or Violation of These Terms Vitatoken maintains full custody of the Digital Assets, funds and User data/information which may be turned over to governmental authorities in the event of Vitatoken Accounts’ suspension/closure arising from fraud investigations, investigations of violation of law or violation of these Terms.',
                ]
            },
            {
                index: 'VII',
                title: 'VII. No Financial Advice',
                textList: [
                    'Vitatoken is not your broker, intermediary, agent, or advisor and has no fiduciary relationship or obligation to you in connection with any trades or other decisions or activities effected by you using Vitatoken Services. No communication or information provided to you by Vitatoken is intended as, or shall be considered or construed as, investment advice, financial advice, trading advice, or any other sort of advice. Unless otherwise specified in these Terms, all trades are executed automatically, based on the parameters of your order instructions and in accordance with posted trade execution procedures, and you are solely responsible for determining whether any investment, investment strategy or related transaction is appropriate for you according to your personal investment objectives, financial circumstances and risk tolerance, and you shall be solely responsible for any loss or liability therefrom. You should consult legal or tax professionals regarding your specific situation. Vitatoken does not recommend that any Digital Asset should be bought, earned, sold, or held by you. Before making the decision to buy, sell or hold any Digital Asset, you should conduct your own due diligence and consult your financial advisors prior to making any investment decision. Vitatoken will not be held responsible for the decisions you make to buy, sell, or hold Digital Asset based on the information provided by Vitatoken.'
                ]
            },
            {
                index: 'VIII',
                title: 'VIII. Compliance with Local',
                textList: [
                    'It is Users’ responsibility to abide by local laws in relation to the legal usage of Vitatoken Services in their local jurisdiction as well as other laws and regulations applicable to Users. Users must also factor, to the extent of their local laws all aspects of taxation, the withholding, collection, reporting and remittance to their appropriate tax authorities. ALL USERS OF VITATOKEN SERVICES ACKNOWLEDGE AND DECLARE THAT THEIR FUNDS COME FROM LEGITIMATE SOURCES AND DO NOT ORIGINATE FROM ILLEGAL ACTIVITIES; USERS AGREE THAT VITATOKEN WILL REQUIRE THEM TO PROVIDE OR OTHERWISE COLLECT THE NECESSARY INFORMATION AND MATERIALS AS PER RELEVANT LAWS OR GOVERNMENT ORDERS TO VERIFY THE LEGALITY OF THE SOURCES AND USE OF THEIR FUNDS. Vitatoken maintains a stance of cooperation with law enforcement authorities globally and will not hesitate to seize, freeze, terminate Users’ accounts and funds which are flagged out or investigated by legal mandate.'
                ]
            },
            {
                index: 'IX',
                title: 'IX. Privacy Policy',
                textList: [
                    'Access to Vitatoken Services will require the submission of certain personally identifiable information. Please review Vitatoken’s Privacy Policy at www.vitatoken.io for a summary of Vitatoken’s guidelines regarding the collection and use of personally identifiable information.'
                ]
            },
            {
                index: 'X',
                title: 'X. Resolving Disputes: Forum, Arbitration, Class Action Waiver',
                textList: [
                    'PLEASE READ THIS SECTION CAREFULLY, AS IT INVOLVES A WAIVER OF CERTAIN RIGHTS TO BRING LEGAL PROCEEDINGS, INCLUDING AS A CLASS ACTION.',
                    'Notice of Claim and Dispute Resolution Period. Please contact Vitatoken first! Vitatoken wants to address your concerns without resorting to formal legal proceedings, if possible. If you have a dispute with Vitatoken, then you should contact Vitatoken and a ticket number will be assigned. Vitatoken will attempt to resolve your dispute internally as soon as possible. The parties agree to negotiate in good faith to resolve the dispute (which discussions shall remain confidential and be subject to applicable rules protecting settlement discussions from use as evidence in any legal proceeding).',
                    'In the event the dispute cannot be resolved satisfactorily, and you wish to assert a legal claim against Vitatoken, then you agree to set forth the basis of such claim in writing in a “Notice of Claim,” as a form of prior notice to Vitatoken. The Notice of Claim must (1) describe the nature and basis of the claim or dispute, (2) set forth the specific relief sought, (3) provide the original ticket number, and (4) include your Vitatoken account email. The Notice of Claim should be submitted to an email address or hyperlink provided in your correspondence with Vitatoken. After you have provided the Notice of Claim to Vitatoken, the dispute referenced in the Notice of Claim may be submitted by either Vitatoken or you to arbitration in accordance with paragraph 2 of this Section, below. For the avoidance of doubt, the submission of a dispute to Vitatoken for resolution internally and the delivery of a Notice of Claim to Vitatoken are prerequisites to commencement of an arbitration proceeding (or any other legal proceeding). During the arbitration, the amount of any settlement offer made by you or Vitatoken shall not be disclosed to the arbitrator.',
                    'Agreement to Arbitrate and Governing Law. You and Vitatoken Operators agree that, subject to paragraph 1 above, any dispute, claim, or controversy between you and Vitatoken (and/or Vitatoken Operators) arising in connection with or relating in any way to these Terms or to your relationship with Vitatoken (and/or Vitatoken Operators) as a user of Vitatoken Services (whether based in contract, tort, statute, fraud, misrepresentation, or any other legal theory, and whether the claims arise during or after the termination of these Terms) will be determined by mandatory final and binding individual (not class) arbitration, except as set forth below under Exceptions to Agreement to Arbitrate. You and Vitatoken Operators further agree that the arbitrator shall have the exclusive power to rule on his or her own jurisdiction, including without limitation any objections with respect to the existence, scope or validity of the Agreement to Arbitrate, or to the arbitrability of any claim or counterclaim. Arbitration is more informal than a lawsuit in court. THERE IS NO JUDGE OR JURY IN ARBITRATION, AND COURT REVIEW OF AN ARBITRATION AWARD IS LIMITED. There may be more limited discovery than in court. The arbitrator must follow this agreement and can award the same damages and relief as a court (including, if applicable, attorney fees), except that the arbitrator may not award declaratory or injunctive relief in favour of anyone but the parties to the arbitration. The arbitration provisions set forth in this Section will survive termination of these Terms. Arbitration Rules. The arbitration shall be subject to the HKIAC Administered Arbitration Rules (HKIAC. Rules) in force when the Notice of Arbitration is submitted, as modified by this Section X. The arbitration will be administered by the Hong Kong International Arbitration Centre (HKIAC). Unless the parties agree otherwise, there shall be only one arbitrator appointed in accordance with the HKIAC Rules. Any arbitration will be conducted in the English language. Regardless of the manner in which the arbitration is conducted, the arbitrator shall issue a reasoned written decision sufficient to explain the essential findings and conclusions on which the decision and award, if any, are based. JUDGMENT ON ANY ARBITRAL AWARD MAY BE GIVEN IN ANY COURT HAVING JURISDICTION OVER THE PARTY (OR OVER THE ASSETS OF THE PARTY) AGAINST WHOM SUCH AN AWARD IS RENDERED. Time for Filing:',
                    'ANY ARBITRATION AGAINST VITATOKEN OPERATORS MUST BE COMMENCED BY FILING A REQUEST FOR ARBITRATION WITHIN ONE (1) YEAR, AFTER THE DATE THE PARTY ASSERTING THE CLAIM FIRST KNOWS OR REASONABLY SHOULD KNOW OF THE ACT, OMISSION OR DEFAULT GIVING RISE TO THE CLAIM; AND THERE SHALL BE NO RIGHT TO ANY REMEDY FOR ANY CLAIM NOT ASSERTED WITHIN THAT TIME PERIOD.',
                    'THIS ONE YEAR LIMITATION PERIOD IS INCLUSIVE OF THE INTERNAL DISPUTE RESOLUTION PROCEDURE SET FORTH IN PARAGRAPH 1 OF THIS SECTION, ABOVE. THERE SHALL BE NO RIGHT TO ANY REMEDY FOR ANY CLAIM NOT ASSERTED WITHIN THAT TIME PERIOD. If applicable law prohibits a one-year limitation period for asserting claims, any claim must be asserted within the shortest time period permitted by applicable law. Process; Notice: The party who intends to seek arbitration after the expiration of the Dispute Resolution Period set forth in paragraph 1, above, must submit a request to the HKIAC in accordance with the HKIAC Rules. If we request arbitration against you, we will give you notice at the email address or mailing address you have provided. You agree that any notice sent to this email or mailing address shall be deemed effective for all purposes, including without limitation to determinations of adequacy of service. It is your obligation to ensure that the email address and/or mailing address on file with Vitatoken is up-to-date and accurate. Seat of Arbitration: The seat of the arbitration shall be Hong Kong. Place of Hearing: The location of any in-person arbitration hearing shall be Hong Kong, unless otherwise agreed to by the parties. Governing Law: These Terms (including this arbitration agreement) shall be governed by, and construed in accordance with, the laws of Hong Kong. Confidentiality. The parties agree that the arbitration shall be kept confidential. The existence of the arbitration, any nonpublic information provided in the arbitration, and any submissions, orders or awards made in the arbitration (together, the “Confidential Information”) shall not be disclosed to any non-party except the tribunal, the HKIAC, the parties, their counsel, experts, witnesses, accountants and auditors, insurers and reinsurers, and any other person necessary to the conduct of the arbitration. Notwithstanding the foregoing, a party may disclose Confidential Information to the extent that disclosure may be required to fulfill a legal duty, protect or pursue a legal right, or enforce or challenge an award in bona fide legal proceedings. This confidentiality provision shall survive termination of these Terms and of any arbitration brought pursuant to these Terms.',
                    'Class Action Waiver. You and Vitatoken agree that any claims relating to these Terms or to your relationship with Vitatoken as a user of Vitatoken Services (whether based in contract, tort, statute, fraud, misrepresentation, or any other legal theory, and whether the claims arise during or after the termination of these Terms) shall be brought against the other party in an arbitration on an individual basis only and not as a plaintiff or class member in a purported class or representative action. You and Vitatoken further agree to waive any right for such claims to be brought, heard, or arbitrated as a class, collective, representative, or private attorney general action, to the extent permissible by applicable law. Combining or consolidating individual arbitrations into a single arbitration is not permitted without the consent of all parties, including Vitatoken.',
                    'Modifications. Vitatoken reserves the right to update, modify, revise, suspend, or make any future changes to Section X regarding the parties’ Agreement to Arbitrate, subject to applicable law. You hereby consent and agree that it is your responsibility to ensure that your understanding of this Section is up to date. Subject to the applicable law, your continued use of your Vitatoken account shall be deemed to be your acceptance of any modifications to Section X regarding the parties’ Agreement to Arbitrate. You agree that if you object to the modifications to Section X, Vitatoken may block access to your account pending closure of your account. In such circumstances, the Terms of Use prior to modification shall remain in full force and effect pending closure of your account.',
                    'Severability. If any portion of these Terms are adjudged to be invalid or unenforceable for any reason or to any extent, the remainder of these Terms will remain valid and enforceable and the invalid or unenforceable portion will be given effect to the greatest extent permitted by law. pending closure of your account.'
                ]
            },
            {
                index: 'XI',
                title: 'XI. Miscellaneous',
                textList: [
                    'Independent Parties.Vitatoken is an independent contractor but not an agent of you in the performance of these Terms. These Terms shall not be interpreted as facts or evidence of an association, joint venture, partnership, or franchise between the parties.',
                    'Entire Agreement.These Terms constitute the entire agreement between the parties regarding use of Vitatoken Services and will supersede all prior written or oral agreements between the parties. No usage of trade or other regular practice or method of dealing between the parties will be used to modify, interpret, supplement, or alter the terms herein. Interpretation and Revision. Vitatoken reserves the right to alter, revise, modify, and/or change these Terms at any time. All changes will take effect immediately upon being published on Vitatoken websites. It is your responsibility to regularly check relevant pages on our websites/applications to confirm the latest version of these Terms. If you do not agree to any such modifications, your only remedy is to terminate your usage of Vitatoken Services and cancel your account. You agree that, unless otherwise expressly provided in these Terms, Vitatoken will not be responsible for any modification or termination of Vitatoken Services by you or any third party, or suspension or termination of your access to Vitatoken Services.',
                    'Force Majeure.Vitatoken will not be liable for any delay or failure to perform as required by these Terms because ofany cause or condition beyond Vitatoken’s reasonable control.',
                    'Severability.If any portion of these Terms is held invalid or unenforceable, such invalidity or enforceability will not affect the other provisions of these Terms, which will remain in full force and effect, and the invalid or unenforceable portion will be given effect to the greatest extent possible.',
                    'Assignment.under these Terms without prior written consent from Vitatoken, including any right or obligation related to the enforcement of laws or the change of control. Vitatoken may assign or transfer any or all of its rights or obligations under these Terms, in whole or in part, without notice or obtaining your consent or approval.',
                    'Waiver.The failure of one party to require performance of any provision will not affect that party’s right to require performance at any time thereafter. At the same time, the waiver of one party to seek recovery for the other party’s violation of these Terms or any provision of applicable terms shall not constitute a waiver by that party of any subsequent breach or violation by the other party or of the provision itself.',
                    'Third-Party Website Disclaimer.Any links to third-party websites from Vitatoken Services does not imply endorsement by Vitatoken of any product, service, information or disclaimer presented therein, nor does Vitatoken guarantee the accuracy of the information contained on them. If you suffer loss from using such third-party product and service, Vitatoken will not be liable for such loss. In addition, since Vitatoken has no control over the terms of use or privacy policies of third-party websites, you should read and understand those policies carefully.',
                    'Matters Related to Apple Inc.If you use any device manufactured by Apple Inc. to participate in any commercial activities or reward programs through Vitatoken Services, such activities and programs are provided by Vitatoken and are not associated with Apple Inc. in any manner.',
                    'Contact Information.For more information on Vitatoken, you may refer to the company and license information found on Vitatoken websites. If you have questions regarding these Terms, please feel free to contact Vitatoken for clarification via our Customer Support team at 10. Contact Information. For more information on Vitatoken, you may refer to the company and license information found on Vitatoken websites. If you have questions regarding these Terms, please feel free to contact Vitatoken for clarification via our Customer Support team at www.vitatoken.io.'
                ]
            },
        ]
        return {
            contentList
        }
    }
}
</script>

<style lang="scss" scoped>
.terms{
    width: 100%;
    color:#333;
    background: #fff;
    padding: 60px 0 40px;
    .content{
        width: 1200px;
        text-align: left;
        font-size: 14px;
        line-height: 21px;
        margin:0 auto;
        &_section{
            margin-bottom: 40px;
            .text{
                margin-bottom: 20px;
                font-size: 14px;
                display:block;
                &-indent{text-indent: 28px;}
            }
            .title{font-size: 16px;margin-bottom: 20px;}
        }
    }
    .title{ color: #ebb650; }
}
</style>
